name: DevOps CI Pipeline

on:
  push:
    branches:
      - main
      - monitoring-script

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Show Repository Files
        run: ls -R

      - name: Make script executable
        run: chmod +x scripts/health-check.sh

      - name: Run Monitoring Script
        run: ./scripts/health-check.sh
